config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products
  root 'store#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Syndishop", root_path, class: "navbar-brand" %>

    </div>
    <ul class="nav navbar-nav navbar-right">



        <% if user_signed_in? && current_user.admin? %>
        <li>
          <%= link_to "My orders", orders_path %>
        </li>
        <li>
          <%= link_to "Products", products_path %>
        </li>
        <li>
          <%= link_to "Admin", rails_admin_path %>
        </li>
        <li>
          <%= link_to "Edit profile", edit_user_registration_path %>
        </li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>
        <% elsif user_signed_in? %>
        <li>
          <%= link_to "My orders", orders_path %>
        </li>
        <li>
          <%= link_to "Edit profile", edit_user_registration_path %>
        </li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
        <li>
          <%= link_to "Sign in", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <% end %>
    </ul>
  </div>
</nav>